apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        ports:
        - containerPort: {{ .Values.containerPort }} 
        resources:
          requests:
            memory: {{ .Values.resources.reqeusts.memory }}
            cpu: {{ .Values.resources.reqeusts.CPU }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.CPU }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 10