namespace:
  name: staging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: yfann/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  reqeusts:
    memory: "90Mi"
    CPU: "300m"
  limits:
    momory: "128Mi"
    CPU: "500m"

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz
